import { StyleSheet,StatusBar } from "react-native";

export const styles = StyleSheet.create({
    safeArea:{
        marginTop:StatusBar.currentHeight
    },
    container:{
        alignItems:"center"
    },
    logo:{
        marginTop:30,
        width:150,
        height:150,

    },
    title:{
        marginTop:"5%",
        textAlign:"center",
        fontSize:24,
        fontWeight:"bold",
    },
    subtitle:{
        margin:"2%",
        textAlign:"center",
        fontSize:16,
        color:"#bbb"
    },
    label:{
        color:"#888",
        fontWeight:"bold",
        padding:10,
        marginHorizontal:10,
        marginTop:20,
        alignSelf:"flex-start"
    },
    input:{
        width:"90%",
        paddingVertical:10,
        paddingHorizontal:20,
        marginHorizontal:15,
        borderWidth:1,
        borderColor:"#ccc",
        borderRadius:8
    },
    loginBtn:{
        width:"90%",
        marginTop:10,
        padding:20,
        marginHorizontal:"5%",
        borderRadius:5,
        backgroundColor:"#4061b7",
        
    },
    loginText:{
        alignSelf:"center",
        color:"#fff",
        fontWeight:"bold"
    },
    forgotPwd:{
        width:"100%",
        padding:20
    },
    forgotPwdText:{
        fontWeight:"bold",
        alignSelf:"flex-end",
        color:"#4061b7",
    },
    signUp:{
        flexDirection:"row",
        marginTop:20,
    },
    signUpText:{
        padding:3,
        fontWeight:"bold",
        color:"#888",
    },
    signUpBtn:{
        padding:3
    },
    signUpBtnText:{
        fontWeight:"bold",
        color:"#4061b7",
        alignSelf:"center"
    },
    checkArea:{
        backgroundColor:"#f00"
    }
})